Models/Venta.cs
using System;
using System.Collections.Generic;

namespace punto.Models
{
    public partial class Venta
    {
        public Venta()
        {
            DetalleVenta = new HashSet<DetalleVenta>();
        }

        public int IdVenta { get; set; }
        public string Producto { get; set; }
        public decimal? Precio { get; set; }
        public int? Cantidad { get; set; }
        public string Cliente { get; set; }
        public DateTime? Fecha { get; set; }
        public decimal? Total { get; set; }

        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
    }
}

Controllers/VentaController.cs
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Microsoft.AspNetCore;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using punto.Models;


    namespace punto.Controllers
    {
        public class VentaController : Controller
        {
            MyDbContext db = new MyDbContext();

            [HttpGet] 
            public ActionResult Index()
            {
                return View(db.Venta.ToList());
            }

            public ActionResult Create()
            {    
                var lista = new Producto();    
                lista.Listasnom = db.Producto.ToList();

                return View(lista);
            }   

            public IActionResult GetProduct(int id)
            {
                    var selectProduct = db.Producto.Find(id);
                    return Json(selectProduct);
            }

            [HttpPost]
            public JsonResult InsertVentas([FromBody]List<Venta> venta)
            {       
                //Check for NULL.
                if (venta == null)
                {
                    venta = new List<Venta>();
                }
        
                //Loop and insert records.
                foreach (Venta ventaa in venta)
                {
                    db.Venta.Add(ventaa);
                }
                int insertedRecords = db.SaveChanges();
                return Json(insertedRecords);
                
            }

            [HttpPost]
            public bool Delete(int id){
                try
                {
                    Venta venta = db.Venta.Where(s => s.IdVenta == id).First();
                    db.Venta.Remove(venta);
                    db.SaveChanges();
                    return true;
                }
                catch (System.Exception)
                {
                    return false;
                }
                
            }           
        }
    }

Views/Venta/Create.cshtml
    @model punto.Models.Producto

    @{    
    ViewData["Title"] = "Realizar Venta - ";    
    } 


    <!-- Content Header (Page header) -->
    
    <section class="content-header">
        <h1>
        Ventas
        </h1>

        <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i> Inicio </a></li>
        <li><a href="~/Venta/Index"><i class="fa fa-circle-o-notch"></i> Ventas </a></li>
        <li class="active">Agregar</li>
        </ol>

    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <!-- Horizontal Form -->
        <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Realizar Venta</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post" action="">
            <div class="box-body">       
                <div class="form-group">
                    <label for="" class="col-sm-1 control-label">Producto</label>
                    <div class="col-sm-10">
                            @Html.DropDownListFor(model => model.Id, Model.ProductoListItems, "Elegir Producto", new { @class = "form-control", id="selectlist"}) 
                    </div>                      
                    <input onclick="Ambas()" id="btnCreate" class="btn btn-success" value="Agregar" style="width:100px">
                </div>                
            </div>
            <div class="box-body">
            <table id="tPedidos" width="100%" class="table table-bordered table-responsive">
                <thead>
                <tr>                  
                    <th style="text-align: center" width= "50%">Producto</th>
                    <th style="text-align: center" width= "30%">Precio</th>
                    <th style="text-align: center" width= "10%">Cantidad</th>
                    <th style="text-align: center" width= "10%">Accion</th>                  
                </tr>
                </thead>
                <tbody></tbody>        
           </table>

            <div class="form-group">
            <br>
            <label class="col-sm-1 control-label">Total</label>
            <div class="col-sm-2">
            <input type="text" style="text-align: center" id="tot" value="0" class="form-control" readonly>                      
            </div> 
            <img src="../dist/img/actualizar.png" width="30" height="31" onclick="CalcularTotal()"/>          
            </div>        

           </div>
            <!-- /.box-body -->
            <div class="box-footer">
            <a href="./"><button type="button" class="btn btn-default">Cancelar</button></a>
            <input onclick="Guardar()" id="btnSave" class="btn btn-info pull-right" value="Crear" style="width:100px">
            </div>
            <!-- /.box-footer -->
        </form>
        </div>
        <!-- /.box -->
    </section>
                
    <script type="text/javascript"> 
    //Opcion para disabled la primera opcion del dropdownlist
    $("#selectlist option:first-child").attr("disabled","disabled");   

    //Funcion Eliminar Fila de la tabla
    function Remove(button) { button.parentElement.parentElement.remove(); };

    //Opcion Eliminar (( ABSTRAIDO A UNA FUNCION PARA TENER UNA INSTANCIA UNICA ))
    function crearBotonEliminar () {
        const eliminar = document.createElement("img");
        eliminar.src = "../dist/img/eliminar.png";      
        eliminar.style.width = '25px';
        eliminar.style.height = "25px";
        return eliminar;
    }
    //Opcion Cantidad (( ABSTRAIDO A UNA FUNCION PARA TENER UNA INSTANCIA UNICA ))
    function crearBotonCantidad () {
        const cantidad = document.createElement('input')
        cantidad.type = 'number'
        cantidad.style.width = '147px'
        cantidad.style.height = '30px'
        cantidad.value= '1'
        cantidad.min = '1'
        cantidad.style.textAlign = "center"
        cantidad.className = 'form-control'
        return cantidad;
    }
    function Ambas () {
        Seleccionar(); 
        //Delay para que ingrese los valores la funcion seleccionar
        setTimeout(CalcularTotal, 100);  
        CalcularTotal();    
    }

    function Seleccionar() {       
        var id = $("#selectlist").val()
        $.ajax({
            type: "GET",
            url: "/Venta/GetProduct?Id=" + id,
            success: function (data) {
                var tBody = $("#tPedidos > TBODY")[0];
                var row = tBody.insertRow(-1);
            
                //Add Nombre cell. 
                cell = $(row.insertCell(0));
                cell.html(data.nombre);
                $(cell).css({"text-align":"center"});

                //Add Precio cell.
                cell = $(row.insertCell(1));
                cell.html("Q" + data.precio)
                $(cell).css({"text-align":"center"});

                //Add Cantidad cell
                cell = $(row.insertCell(2));
                cantidad = crearBotonCantidad();
                cell.html(cantidad) 
                $(cell).css({"width":"10%"}); 
                cantidad.onchange = function(){
                   CalcularTotal(); 
                }          
                
                //Add Eliminar cell
                cell = $(row.insertCell(3));
                eliminar = crearBotonEliminar();
                cell.html(eliminar);
                $(cell).css({"width":"10%","text-align":"center"});
                //Despues de mostrar-lo en el HTML
                eliminar.onclick = function(){
                Remove(this);
                CalcularTotal();
                };

            }
        });
    };   

    function Guardar() {
            //Loop through the Table rows and build a JSON array.
            var ventas = new Array();
            //Fecha y Hora
            var today = new Date();
            var n = today.getTime();
            var date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
            var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
            var dateTime = date+' '+time;

            $("#tPedidos TBODY TR").each(function () {
                var row = $(this);
                var venta = {};
                venta.Producto = row.find("TD").eq(0).html();

                pre = row.find("TD").eq(1).html();
                venta.Precio = pre.split('Q')[1];

                venta.Cantidad = row.find("TD").eq(2).find('input').val();

                venta.Total = venta.Precio * venta.Cantidad;
                venta.Cliente = "Brian";
                venta.Fecha = dateTime;
                
                
                ventas.push(venta);
            }); 
        
            
            //tot = $("#tot").val();  
            //console.log("Total: " + tot);

            //ventas[3].push(tot); 
            //ventas.splice(3, 0, tot);
                             
 
            //Send the JSON array to Controller using AJAX.
            $.ajax({
                type: "POST",
                url: "/Venta/InsertVentas",
                data: JSON.stringify(ventas),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function () {
                    alert("Venta realizada!");
                    location.reload();
                }
            }
            );
            console.log(ventas);
        };
    
    function CalcularTotal () {
        var subtotal = 0;
        var total = 0;
        $("#tPedidos TBODY TR").each(function () {
                var row = $(this);

                //Valor de Precio
                pre = row.find("TD").eq(1).html();
                const Precio = pre.split('Q')[1];
                //Valor de Cantidad
                CantidadPedido = row.find("TD").eq(2).find('input').val();

                //subtotal de PRECIO * CAntidad y Total de cada fila
                subtotal = Precio * CantidadPedido;
                total += Number(subtotal);
                
            });

            //Asignarle el valor al input
            $("#tot").val(total);
            //console.log(total);          
    }

    </script> 

Views/Venta/Index.cshtml
    @model IEnumerable<punto.Models.Venta>

        @{    
             ViewData["Title"] = "Ventas - ";    
        }   

    <section class="content-header">
        <h1>
        Ventas
        </h1>
        <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Inicio </a></li>
        <li class="active">Ventas</li>
        </ol>
        
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
        <div class="col-xs-12">
            <div class="box">
            <div class="box-header">
                <h3 class="box-title">Manejar Venta</h3>
                <a href="~/Venta/Create"><button type="button" class="btn btn-success pull-right">Agregar Venta</button></a>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr> 
                    <th style="display:none;">Id</th>                 
                    <th style="text-align: center;">Producto</th>
                    <th style="text-align: center;">Precio</th>
                    <th style="text-align: center;">Cantidad</th>
                    <th style="text-align: center;">Subtotal</th>
                    <th style="text-align: center;">Cliente</th>
                    <th style="text-align: center;">Fecha</th>
                    <th style="text-align: center;">Accion</th>
                </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="display:none;">@Html.DisplayFor(modelItem => item.IdVenta)</td>
                            <td>@Html.DisplayFor(modelItem => item.Producto)</td>
                            <td style="text-align: center;">Q @Html.DisplayFor(modelItem => item.Precio)</td>
                            <td style="text-align: center;">@Html.DisplayFor(modelItem => item.Cantidad)</td>
                            <td style="text-align: center;">Q @Html.DisplayFor(modelItem => item.Total)</td>
                            <td style="text-align: center;">@Html.DisplayFor(modelItem => item.Cliente)</td>
                            <td style="text-align: center;">@Html.DisplayFor(modelItem => item.Fecha)</td>                                            
                            <td style="text-align: center;"><a href="" onclick="Delete('@item.IdVenta')"><img src="../dist/img/eliminar.png" width="25" height="25"/></a></td>
                        </tr>
                    }
                </table>

                <div class="form-group">
                    <br>
                    <label class="col-sm-1 control-label">Total de Ventas</label>
                    <div class="col-sm-2">
                    <input type="text" style="text-align: center" id="tot" value="Q0.00" class="form-control" readonly>                      
                    </div> 
                    <img src="../dist/img/actualizar.png" width="30" height="31" onclick="CalcularTotal()"/>          
                </div> 

            </div>
            <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
       
    <!-- DataTables -->
    <script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <!-- page script -->
    <script>
        $(function () {
            $('#example1').DataTable( {
                    "language": idioma_español
                } );
        });

        var idioma_español = {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ Registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }

        function CalcularTotal () {
            var subtotal = 0;
            var total = 0;
            $("#example1 TBODY TR").each(function () {
                    var row = $(this);

                    sub = row.find("TD").eq(4).html().split('Q')[1];
                    subtotal = parseFloat(sub.replace(",", "."));

                    //subtotal de PRECIO * CAntidad y Total de cada fila
                    total = total + subtotal;
                    //total += Number(subtotal);
                    //console.log(b);
                    //console.log(subtotal);
                });

                //Asignarle el valor al input
                $("#tot").val("Q" + total);
                console.log(total);          
        }

        function Delete(id){
            var txt;
            var r = confirm("Estas seguro que deseas eliminar esto?");
            if (r == true) {
                
                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("Delete", "Venta")',
                    data: {
                        id: id
                    },
                    error: function (result) {
                        alert("error");
                    },
                    success: function (result) {
                        if (result == true) {
                            var baseUrl="/Pedido";
                            window.location.reload();
                        }
                        else {
                            alert("Hay un problema, Intenta Despues!");
                        }
                    }
                });
            } 
        }
    </script>

Views/Venta/_test.cshtml
@model punto.Models.Cliente

                    <label for="" class="col-sm-1 control-label">Producto</label>
                    <div class="col-sm-10">
                            @Html.DropDownListFor(model => model.IdCliente, Model.ClienteListItems , "Elegir Cliente", new { @class = "form-control", id="selectlist2"}) 
                    </div>